export const SET_LEARNING_RATE = 'SET_LEARNING_RATE';
export const SET_LEARNING_LIMIT = 'SET_LEARNING_LIMIT';
export const SET_NODE_PER_LAYER = 'SET_NODE_PER_LAYER';
export const SET_LAYER_COUNT = 'SET_LAYER_COUNT';
export const SET_INPUTS = 'SET_INPUTS';

export const SET_NODE_GRAPHIC_DATA = 'SET_NODE_GRAPHIC_DATA';

export const SET_ERROR_DATASET = 'SET_ERROR_DATASET';
export const SET_OUTPUT_DATASET = 'SET_OUTPUT_DATASET';

export const SET_LEARNING_RESULT = 'SET_LEARNING_RESULT';
export const SET_TOTAL_LOSS = 'SET_TOTAL_LOSS';
